/**
 * Revenue Tier Scoring
 * 
 * Auto-calibrated revenue tiers that scale based on account size.
 * Rewards absolute revenue generation, not just efficiency.
 * 
 * A small boutique account generating $5k/step and a large account generating $50k/step
 * should both score well if they're performing at their scale.
 */

/**
 * Default revenue tier thresholds for a ~$100k account (baseline).
 * These get scaled by the account's actual revenue.
 */
const DEFAULT_TIERS = [
    { threshold: 50000, points: 35 },  // $50k+ → max points
    { threshold: 25000, points: 30 },
    { threshold: 10000, points: 25 },
    { threshold: 5000, points: 20 },
    { threshold: 2000, points: 15 },
    { threshold: 500, points: 10 },
    { threshold: 0, points: 5 },       // Any revenue → minimum points
];

/**
 * Baseline account revenue for tier scaling.
 * Accounts with this revenue use the default thresholds.
 */
const BASELINE_ACCOUNT_REVENUE = 100_000;

/**
 * Minimum multiplier to prevent thresholds from becoming too small
 */
const MIN_MULTIPLIER = 0.1;

/**
 * Maximum multiplier to prevent thresholds from becoming absurdly high
 */
const MAX_MULTIPLIER = 10;

/**
 * Calculate the tier multiplier based on account's total flow revenue.
 * 
 * @param accountFlowRevenue - Total revenue from all flows in the account for the date range
 * @returns Multiplier for revenue tier thresholds
 */
export function calculateTierMultiplier(accountFlowRevenue: number): number {
    if (accountFlowRevenue <= 0) return MIN_MULTIPLIER;
    
    const rawMultiplier = accountFlowRevenue / BASELINE_ACCOUNT_REVENUE;
    
    return Math.max(MIN_MULTIPLIER, Math.min(MAX_MULTIPLIER, rawMultiplier));
}

/**
 * Get the calibrated revenue tiers for an account.
 * 
 * @param accountFlowRevenue - Total revenue from all flows in the account
 * @returns Array of tier thresholds scaled to the account
 */
export function getCalibratedTiers(accountFlowRevenue: number): Array<{ threshold: number; points: number }> {
    const multiplier = calculateTierMultiplier(accountFlowRevenue);
    
    return DEFAULT_TIERS.map(tier => ({
        threshold: tier.threshold * multiplier,
        points: tier.points
    }));
}

/**
 * Calculate absolute revenue points for a step (0-35 max).
 * Rewards steps that generate real dollars, scaled to the account's size.
 * 
 * @param stepRevenue - Revenue generated by this step in the date range
 * @param accountFlowRevenue - Total revenue from all flows in the account
 * @returns Points from 0-35 based on absolute revenue
 */
export function getAbsoluteRevenuePoints(
    stepRevenue: number,
    accountFlowRevenue: number
): { points: number; tier: number; threshold: number } {
    const tiers = getCalibratedTiers(accountFlowRevenue);
    
    for (let i = 0; i < tiers.length; i++) {
        if (stepRevenue >= tiers[i].threshold) {
            return {
                points: tiers[i].points,
                tier: i + 1,
                threshold: tiers[i].threshold
            };
        }
    }
    
    // Should never reach here, but fallback to minimum
    return { points: 5, tier: tiers.length, threshold: 0 };
}

/**
 * Get a human-readable description of the revenue tier.
 */
export function getRevenueTierDescription(tier: number): string {
    switch (tier) {
        case 1: return 'Exceptional revenue';
        case 2: return 'Strong revenue';
        case 3: return 'Good revenue';
        case 4: return 'Moderate revenue';
        case 5: return 'Low revenue';
        case 6: return 'Minimal revenue';
        default: return 'Very low revenue';
    }
}

/**
 * Format revenue thresholds for display.
 * Uses account-calibrated thresholds to show contextual targets.
 */
export function formatThresholdForDisplay(threshold: number): string {
    if (threshold >= 1000) {
        return `$${(threshold / 1000).toFixed(threshold >= 10000 ? 0 : 1)}k`;
    }
    return `$${threshold.toFixed(0)}`;
}

/**
 * Calculate the money pillar score combining efficiency (Revenue Index) and absolute revenue.
 * Total max: 70 points (35 for RI + 35 for absolute revenue)
 * 
 * @param revenuePerEmail - RPE for this step
 * @param medianRPE - Median RPE across all steps in the flow
 * @param stepRevenue - Total revenue from this step
 * @param accountFlowRevenue - Total account flow revenue for calibration
 * @returns Combined money pillar points and breakdown
 */
export function calculateMoneyPillarScore(
    revenuePerEmail: number,
    medianRPE: number,
    stepRevenue: number,
    accountFlowRevenue: number
): {
    totalPoints: number;
    riPoints: number;
    riValue: number;
    absoluteRevenuePoints: number;
    absoluteRevenueTier: number;
} {
    // Revenue Index (efficiency): 0-35 points
    // RI = RPE / medianRPE, clipped to [0, 2.0], then scaled to 35 points
    const riRaw = medianRPE > 0 ? revenuePerEmail / medianRPE : 0;
    const riClipped = Math.max(0, Math.min(2.0, riRaw));
    const riPoints = 35 * (riClipped / 2);
    
    // Absolute revenue: 0-35 points (calibrated to account size)
    const absoluteResult = getAbsoluteRevenuePoints(stepRevenue, accountFlowRevenue);
    
    return {
        totalPoints: Math.min(70, riPoints + absoluteResult.points),
        riPoints,
        riValue: riClipped,
        absoluteRevenuePoints: absoluteResult.points,
        absoluteRevenueTier: absoluteResult.tier
    };
}
